CREATE TABLE critics(
    critic_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    preferred_name varchar(100),
    surname varchar(50),
    organization_name varchar(100),
    timestamps TRUE TRUE 
)