CREATE TABLE theaters(
    theater_id INTEGER PRIMARY KEY generated by default AS identity,
    name varchar(50),
    address_line_1 varchar(50),
    address_line_2 varchar(50),
    city varchar(50),
    state varchar(15),
    zip varchar(5),
    timestamps TRUE TRUE
)